baseurl: ''
exclude: ['README.md']
permalink: pretty
title: '3D Language'

google_analytics_id: UA-91106496-2
homepage:
  show_call_box: false
logo:
  mobile: "images/logo.svg"
  desktop: "images/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: ''

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

